// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6UCuXqQEJ1x6eW9xM33DruKfnxBN-nU',
    appId: '1:486846432381:web:5af4efb2098f1e08d25d14',
    messagingSenderId: '486846432381',
    projectId: 'auto-sense-test',
    authDomain: 'auto-sense-test.firebaseapp.com',
    storageBucket: 'auto-sense-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTSDYnoOpJXh2UMmACf0w45kHpb6IhQc',
    appId: '1:486846432381:android:0b6a544d8068ebf9d25d14',
    messagingSenderId: '486846432381',
    projectId: 'auto-sense-test',
    storageBucket: 'auto-sense-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3Vr7JBTPWJF7kIXjVxEZfR7GxOvUt3U',
    appId: '1:486846432381:ios:33cb2e2b96cdf288d25d14',
    messagingSenderId: '486846432381',
    projectId: 'auto-sense-test',
    storageBucket: 'auto-sense-test.appspot.com',
    iosClientId: '486846432381-itkkpjo7vbj001gnfvnb55ao0ei2onb4.apps.googleusercontent.com',
    iosBundleId: 'me.momar.fuelMaps',
  );
}
