name: fuel_maps
description: A new Flutter project.

publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flex_color_scheme: ^5.0.1
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.3
  geolocator: ^8.2.1
  google_fonts: ^2.3.2
  google_maps_flutter: ^2.1.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.5.0
  like_button: ^2.0.4
  path_provider: ^2.0.9
  salomon_bottom_bar: ^3.3.0
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
